name: CloudFunctions Test CI

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0

      - name: Install modules
        run: yarn

      - name: Run tests
        run: yarn ci:test
